# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '/Users/ecabuk/Projects/vlf/ui/inclinometer.ui'
#
# Created by: PyQt4 UI code generator 4.11.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_InclinometerView(object):
    def setupUi(self, InclinometerView):
        InclinometerView.setObjectName(_fromUtf8("InclinometerView"))
        InclinometerView.resize(800, 480)
        InclinometerView.setAutoFillBackground(True)
        self.lcd_x = QtGui.QLCDNumber(InclinometerView)
        self.lcd_x.setGeometry(QtCore.QRect(10, 90, 201, 91))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.lcd_x.setFont(font)
        self.lcd_x.setAutoFillBackground(False)
        self.lcd_x.setStyleSheet(_fromUtf8("color: #00fa4b;\n"
"background-color: #000;"))
        self.lcd_x.setSmallDecimalPoint(False)
        self.lcd_x.setNumDigits(6)
        self.lcd_x.setDigitCount(6)
        self.lcd_x.setMode(QtGui.QLCDNumber.Dec)
        self.lcd_x.setSegmentStyle(QtGui.QLCDNumber.Flat)
        self.lcd_x.setProperty("value", 89.99)
        self.lcd_x.setObjectName(_fromUtf8("lcd_x"))
        self.label_x = QtGui.QLabel(InclinometerView)
        self.label_x.setGeometry(QtCore.QRect(70, 10, 81, 81))
        font = QtGui.QFont()
        font.setPointSize(64)
        self.label_x.setFont(font)
        self.label_x.setAlignment(QtCore.Qt.AlignCenter)
        self.label_x.setObjectName(_fromUtf8("label_x"))
        self.label_y = QtGui.QLabel(InclinometerView)
        self.label_y.setGeometry(QtCore.QRect(360, 10, 81, 81))
        font = QtGui.QFont()
        font.setPointSize(64)
        self.label_y.setFont(font)
        self.label_y.setAlignment(QtCore.Qt.AlignCenter)
        self.label_y.setObjectName(_fromUtf8("label_y"))
        self.lcd_y = QtGui.QLCDNumber(InclinometerView)
        self.lcd_y.setGeometry(QtCore.QRect(300, 90, 201, 91))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.lcd_y.setFont(font)
        self.lcd_y.setAutoFillBackground(False)
        self.lcd_y.setStyleSheet(_fromUtf8("color: #00fa4b;\n"
"background-color: #000;"))
        self.lcd_y.setSmallDecimalPoint(False)
        self.lcd_y.setNumDigits(6)
        self.lcd_y.setDigitCount(6)
        self.lcd_y.setMode(QtGui.QLCDNumber.Dec)
        self.lcd_y.setSegmentStyle(QtGui.QLCDNumber.Flat)
        self.lcd_y.setProperty("value", -89.99)
        self.lcd_y.setObjectName(_fromUtf8("lcd_y"))
        self.button_close = QtGui.QPushButton(InclinometerView)
        self.button_close.setGeometry(QtCore.QRect(350, 430, 110, 41))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.button_close.setFont(font)
        self.button_close.setObjectName(_fromUtf8("button_close"))
        self.lcd_t = QtGui.QLCDNumber(InclinometerView)
        self.lcd_t.setGeometry(QtCore.QRect(590, 90, 201, 91))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.lcd_t.setFont(font)
        self.lcd_t.setAutoFillBackground(False)
        self.lcd_t.setStyleSheet(_fromUtf8("color: #e80010;\n"
"background-color: #000;"))
        self.lcd_t.setSmallDecimalPoint(False)
        self.lcd_t.setNumDigits(6)
        self.lcd_t.setDigitCount(6)
        self.lcd_t.setMode(QtGui.QLCDNumber.Dec)
        self.lcd_t.setSegmentStyle(QtGui.QLCDNumber.Flat)
        self.lcd_t.setProperty("value", -89.99)
        self.lcd_t.setObjectName(_fromUtf8("lcd_t"))
        self.label_t = QtGui.QLabel(InclinometerView)
        self.label_t.setGeometry(QtCore.QRect(650, 10, 81, 81))
        font = QtGui.QFont()
        font.setPointSize(64)
        self.label_t.setFont(font)
        self.label_t.setAlignment(QtCore.Qt.AlignCenter)
        self.label_t.setObjectName(_fromUtf8("label_t"))
        self.line_1 = QtGui.QFrame(InclinometerView)
        self.line_1.setGeometry(QtCore.QRect(0, 200, 801, 20))
        self.line_1.setFrameShape(QtGui.QFrame.HLine)
        self.line_1.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_1.setObjectName(_fromUtf8("line_1"))
        self.line_2 = QtGui.QFrame(InclinometerView)
        self.line_2.setGeometry(QtCore.QRect(0, 410, 801, 20))
        self.line_2.setFrameShape(QtGui.QFrame.HLine)
        self.line_2.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_2.setObjectName(_fromUtf8("line_2"))
        self.horizontalLayoutWidget_4 = QtGui.QWidget(InclinometerView)
        self.horizontalLayoutWidget_4.setGeometry(QtCore.QRect(9, 236, 781, 171))
        self.horizontalLayoutWidget_4.setObjectName(_fromUtf8("horizontalLayoutWidget_4"))
        self.horizontalLayout_5 = QtGui.QHBoxLayout(self.horizontalLayoutWidget_4)
        self.horizontalLayout_5.setObjectName(_fromUtf8("horizontalLayout_5"))
        self.verticalLayout_3 = QtGui.QVBoxLayout()
        self.verticalLayout_3.setObjectName(_fromUtf8("verticalLayout_3"))
        self.label_filter_freq = QtGui.QLabel(self.horizontalLayoutWidget_4)
        font = QtGui.QFont()
        font.setPointSize(18)
        self.label_filter_freq.setFont(font)
        self.label_filter_freq.setObjectName(_fromUtf8("label_filter_freq"))
        self.verticalLayout_3.addWidget(self.label_filter_freq)
        self.label_zero_set = QtGui.QLabel(self.horizontalLayoutWidget_4)
        font = QtGui.QFont()
        font.setPointSize(18)
        self.label_zero_set.setFont(font)
        self.label_zero_set.setWordWrap(False)
        self.label_zero_set.setObjectName(_fromUtf8("label_zero_set"))
        self.verticalLayout_3.addWidget(self.label_zero_set)
        self.label_zero_reset = QtGui.QLabel(self.horizontalLayoutWidget_4)
        font = QtGui.QFont()
        font.setPointSize(18)
        self.label_zero_reset.setFont(font)
        self.label_zero_reset.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_zero_reset.setWordWrap(False)
        self.label_zero_reset.setObjectName(_fromUtf8("label_zero_reset"))
        self.verticalLayout_3.addWidget(self.label_zero_reset)
        self.horizontalLayout_5.addLayout(self.verticalLayout_3)
        spacerItem = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_5.addItem(spacerItem)
        self.verticalLayout_2 = QtGui.QVBoxLayout()
        self.verticalLayout_2.setObjectName(_fromUtf8("verticalLayout_2"))
        self.select_filter_freq = QtGui.QComboBox(self.horizontalLayoutWidget_4)
        font = QtGui.QFont()
        font.setPointSize(18)
        self.select_filter_freq.setFont(font)
        self.select_filter_freq.setSizeAdjustPolicy(QtGui.QComboBox.AdjustToContents)
        self.select_filter_freq.setObjectName(_fromUtf8("select_filter_freq"))
        self.verticalLayout_2.addWidget(self.select_filter_freq)
        self.button_zero_set = QtGui.QPushButton(self.horizontalLayoutWidget_4)
        font = QtGui.QFont()
        font.setPointSize(18)
        self.button_zero_set.setFont(font)
        self.button_zero_set.setObjectName(_fromUtf8("button_zero_set"))
        self.verticalLayout_2.addWidget(self.button_zero_set)
        self.button_zero_reset = QtGui.QPushButton(self.horizontalLayoutWidget_4)
        font = QtGui.QFont()
        font.setPointSize(18)
        self.button_zero_reset.setFont(font)
        self.button_zero_reset.setDefault(False)
        self.button_zero_reset.setFlat(False)
        self.button_zero_reset.setObjectName(_fromUtf8("button_zero_reset"))
        self.verticalLayout_2.addWidget(self.button_zero_reset)
        self.horizontalLayout_5.addLayout(self.verticalLayout_2)
        spacerItem1 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_5.addItem(spacerItem1)

        self.retranslateUi(InclinometerView)
        QtCore.QObject.connect(self.button_close, QtCore.SIGNAL(_fromUtf8("clicked()")), InclinometerView.close)
        QtCore.QMetaObject.connectSlotsByName(InclinometerView)

    def retranslateUi(self, InclinometerView):
        InclinometerView.setWindowTitle(_translate("InclinometerView", "Inclinometer", None))
        self.label_x.setText(_translate("InclinometerView", "X", None))
        self.label_y.setText(_translate("InclinometerView", "Y", None))
        self.button_close.setText(_translate("InclinometerView", "Close", None))
        self.label_t.setText(_translate("InclinometerView", "T", None))
        self.label_filter_freq.setText(_translate("InclinometerView", "Digital filter frequency response", None))
        self.label_zero_set.setText(_translate("InclinometerView", "Set the current position to zero", None))
        self.label_zero_reset.setText(_translate("InclinometerView", "Reset zero to factory settings", None))
        self.button_zero_set.setText(_translate("InclinometerView", "Set", None))
        self.button_zero_reset.setText(_translate("InclinometerView", "Reset", None))

