# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '/Users/ecabuk/Projects/vlf/ui/measurements.ui'
#
# Created by: PyQt4 UI code generator 4.11.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_MeasurementsView(object):
    def setupUi(self, MeasurementsView):
        MeasurementsView.setObjectName(_fromUtf8("MeasurementsView"))
        MeasurementsView.resize(800, 480)
        MeasurementsView.setAutoFillBackground(True)
        self.tabWidget = QtGui.QTabWidget(MeasurementsView)
        self.tabWidget.setGeometry(QtCore.QRect(-1, -1, 800, 480))
        font = QtGui.QFont()
        font.setPointSize(22)
        self.tabWidget.setFont(font)
        self.tabWidget.setAutoFillBackground(False)
        self.tabWidget.setTabShape(QtGui.QTabWidget.Rounded)
        self.tabWidget.setElideMode(QtCore.Qt.ElideRight)
        self.tabWidget.setObjectName(_fromUtf8("tabWidget"))
        self.tab_measure = QtGui.QWidget()
        self.tab_measure.setObjectName(_fromUtf8("tab_measure"))
        self.button_measure = QtGui.QPushButton(self.tab_measure)
        self.button_measure.setGeometry(QtCore.QRect(640, 370, 151, 51))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.button_measure.setFont(font)
        self.button_measure.setObjectName(_fromUtf8("button_measure"))
        self.button_next_station = QtGui.QPushButton(self.tab_measure)
        self.button_next_station.setGeometry(QtCore.QRect(170, 370, 151, 51))
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.button_next_station.sizePolicy().hasHeightForWidth())
        self.button_next_station.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(18)
        self.button_next_station.setFont(font)
        self.button_next_station.setObjectName(_fromUtf8("button_next_station"))
        self.button_prev_station = QtGui.QPushButton(self.tab_measure)
        self.button_prev_station.setGeometry(QtCore.QRect(10, 370, 151, 51))
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.button_prev_station.sizePolicy().hasHeightForWidth())
        self.button_prev_station.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(18)
        self.button_prev_station.setFont(font)
        self.button_prev_station.setObjectName(_fromUtf8("button_prev_station"))
        self.results_table = QtGui.QTableView(self.tab_measure)
        self.results_table.setGeometry(QtCore.QRect(5, 110, 781, 241))
        self.results_table.setStyleSheet(_fromUtf8("QScrollBar:vertical { width: 30px; }"))
        self.results_table.setFrameShadow(QtGui.QFrame.Raised)
        self.results_table.setAlternatingRowColors(True)
        self.results_table.setSelectionMode(QtGui.QAbstractItemView.NoSelection)
        self.results_table.setObjectName(_fromUtf8("results_table"))
        self.results_table.horizontalHeader().setDefaultSectionSize(200)
        self.results_table.horizontalHeader().setMinimumSectionSize(190)
        self.results_table.horizontalHeader().setStretchLastSection(True)
        self.horizontalLayoutWidget = QtGui.QWidget(self.tab_measure)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(10, 10, 251, 41))
        self.horizontalLayoutWidget.setObjectName(_fromUtf8("horizontalLayoutWidget"))
        self.horizontalLayout = QtGui.QHBoxLayout(self.horizontalLayoutWidget)
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.label_profile_num = QtGui.QLabel(self.horizontalLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(18)
        font.setBold(True)
        font.setWeight(75)
        self.label_profile_num.setFont(font)
        self.label_profile_num.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_profile_num.setObjectName(_fromUtf8("label_profile_num"))
        self.horizontalLayout.addWidget(self.label_profile_num)
        self.label_profile_num_val = QtGui.QLabel(self.horizontalLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(16)
        self.label_profile_num_val.setFont(font)
        self.label_profile_num_val.setObjectName(_fromUtf8("label_profile_num_val"))
        self.horizontalLayout.addWidget(self.label_profile_num_val)
        self.horizontalLayoutWidget_2 = QtGui.QWidget(self.tab_measure)
        self.horizontalLayoutWidget_2.setGeometry(QtCore.QRect(270, 10, 251, 41))
        self.horizontalLayoutWidget_2.setObjectName(_fromUtf8("horizontalLayoutWidget_2"))
        self.horizontalLayout_2 = QtGui.QHBoxLayout(self.horizontalLayoutWidget_2)
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        self.label_current_point = QtGui.QLabel(self.horizontalLayoutWidget_2)
        font = QtGui.QFont()
        font.setPointSize(18)
        font.setBold(True)
        font.setWeight(75)
        self.label_current_point.setFont(font)
        self.label_current_point.setObjectName(_fromUtf8("label_current_point"))
        self.horizontalLayout_2.addWidget(self.label_current_point)
        self.label_current_point_val = QtGui.QLabel(self.horizontalLayoutWidget_2)
        font = QtGui.QFont()
        font.setPointSize(16)
        self.label_current_point_val.setFont(font)
        self.label_current_point_val.setObjectName(_fromUtf8("label_current_point_val"))
        self.horizontalLayout_2.addWidget(self.label_current_point_val)
        self.horizontalLayoutWidget_3 = QtGui.QWidget(self.tab_measure)
        self.horizontalLayoutWidget_3.setGeometry(QtCore.QRect(530, 10, 251, 41))
        self.horizontalLayoutWidget_3.setObjectName(_fromUtf8("horizontalLayoutWidget_3"))
        self.horizontalLayout_3 = QtGui.QHBoxLayout(self.horizontalLayoutWidget_3)
        self.horizontalLayout_3.setObjectName(_fromUtf8("horizontalLayout_3"))
        self.label_distance = QtGui.QLabel(self.horizontalLayoutWidget_3)
        font = QtGui.QFont()
        font.setPointSize(18)
        font.setBold(True)
        font.setWeight(75)
        self.label_distance.setFont(font)
        self.label_distance.setObjectName(_fromUtf8("label_distance"))
        self.horizontalLayout_3.addWidget(self.label_distance)
        self.label_distance_val = QtGui.QLabel(self.horizontalLayoutWidget_3)
        font = QtGui.QFont()
        font.setPointSize(16)
        self.label_distance_val.setFont(font)
        self.label_distance_val.setObjectName(_fromUtf8("label_distance_val"))
        self.horizontalLayout_3.addWidget(self.label_distance_val)
        self.horizontalLayoutWidget_4 = QtGui.QWidget(self.tab_measure)
        self.horizontalLayoutWidget_4.setGeometry(QtCore.QRect(9, 59, 251, 41))
        self.horizontalLayoutWidget_4.setObjectName(_fromUtf8("horizontalLayoutWidget_4"))
        self.horizontalLayout_4 = QtGui.QHBoxLayout(self.horizontalLayoutWidget_4)
        self.horizontalLayout_4.setObjectName(_fromUtf8("horizontalLayout_4"))
        self.label_interval = QtGui.QLabel(self.horizontalLayoutWidget_4)
        font = QtGui.QFont()
        font.setPointSize(18)
        font.setBold(True)
        font.setWeight(75)
        self.label_interval.setFont(font)
        self.label_interval.setObjectName(_fromUtf8("label_interval"))
        self.horizontalLayout_4.addWidget(self.label_interval)
        self.label_interval_val = QtGui.QLabel(self.horizontalLayoutWidget_4)
        font = QtGui.QFont()
        font.setPointSize(16)
        self.label_interval_val.setFont(font)
        self.label_interval_val.setObjectName(_fromUtf8("label_interval_val"))
        self.horizontalLayout_4.addWidget(self.label_interval_val)
        self.horizontalLayoutWidget_5 = QtGui.QWidget(self.tab_measure)
        self.horizontalLayoutWidget_5.setGeometry(QtCore.QRect(270, 60, 251, 41))
        self.horizontalLayoutWidget_5.setObjectName(_fromUtf8("horizontalLayoutWidget_5"))
        self.horizontalLayout_5 = QtGui.QHBoxLayout(self.horizontalLayoutWidget_5)
        self.horizontalLayout_5.setObjectName(_fromUtf8("horizontalLayout_5"))
        self.label_frames = QtGui.QLabel(self.horizontalLayoutWidget_5)
        font = QtGui.QFont()
        font.setPointSize(18)
        font.setBold(True)
        font.setWeight(75)
        self.label_frames.setFont(font)
        self.label_frames.setObjectName(_fromUtf8("label_frames"))
        self.horizontalLayout_5.addWidget(self.label_frames)
        self.label_frames_val = QtGui.QLabel(self.horizontalLayoutWidget_5)
        font = QtGui.QFont()
        font.setPointSize(16)
        self.label_frames_val.setFont(font)
        self.label_frames_val.setObjectName(_fromUtf8("label_frames_val"))
        self.horizontalLayout_5.addWidget(self.label_frames_val)
        self.horizontalLayoutWidget_6 = QtGui.QWidget(self.tab_measure)
        self.horizontalLayoutWidget_6.setGeometry(QtCore.QRect(530, 60, 251, 41))
        self.horizontalLayoutWidget_6.setObjectName(_fromUtf8("horizontalLayoutWidget_6"))
        self.horizontalLayout_6 = QtGui.QHBoxLayout(self.horizontalLayoutWidget_6)
        self.horizontalLayout_6.setObjectName(_fromUtf8("horizontalLayout_6"))
        self.label_resolution = QtGui.QLabel(self.horizontalLayoutWidget_6)
        font = QtGui.QFont()
        font.setPointSize(18)
        font.setBold(True)
        font.setWeight(75)
        self.label_resolution.setFont(font)
        self.label_resolution.setObjectName(_fromUtf8("label_resolution"))
        self.horizontalLayout_6.addWidget(self.label_resolution)
        self.label_resolution_val = QtGui.QLabel(self.horizontalLayoutWidget_6)
        font = QtGui.QFont()
        font.setPointSize(16)
        self.label_resolution_val.setFont(font)
        self.label_resolution_val.setStyleSheet(_fromUtf8(""))
        self.label_resolution_val.setObjectName(_fromUtf8("label_resolution_val"))
        self.horizontalLayout_6.addWidget(self.label_resolution_val)
        self.lcd_x = QtGui.QLCDNumber(self.tab_measure)
        self.lcd_x.setGeometry(QtCore.QRect(370, 380, 101, 40))
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lcd_x.sizePolicy().hasHeightForWidth())
        self.lcd_x.setSizePolicy(sizePolicy)
        self.lcd_x.setMinimumSize(QtCore.QSize(0, 40))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.lcd_x.setFont(font)
        self.lcd_x.setStyleSheet(_fromUtf8("color:#000000;"))
        self.lcd_x.setFrameShadow(QtGui.QFrame.Sunken)
        self.lcd_x.setSmallDecimalPoint(False)
        self.lcd_x.setSegmentStyle(QtGui.QLCDNumber.Flat)
        self.lcd_x.setObjectName(_fromUtf8("lcd_x"))
        self.label_tilt_x = QtGui.QLabel(self.tab_measure)
        self.label_tilt_x.setGeometry(QtCore.QRect(330, 380, 41, 40))
        font = QtGui.QFont()
        font.setPointSize(18)
        font.setBold(True)
        font.setWeight(75)
        self.label_tilt_x.setFont(font)
        self.label_tilt_x.setAlignment(QtCore.Qt.AlignCenter)
        self.label_tilt_x.setObjectName(_fromUtf8("label_tilt_x"))
        self.label_tilt_y = QtGui.QLabel(self.tab_measure)
        self.label_tilt_y.setGeometry(QtCore.QRect(470, 380, 41, 40))
        font = QtGui.QFont()
        font.setPointSize(18)
        font.setBold(True)
        font.setWeight(75)
        self.label_tilt_y.setFont(font)
        self.label_tilt_y.setAlignment(QtCore.Qt.AlignCenter)
        self.label_tilt_y.setObjectName(_fromUtf8("label_tilt_y"))
        self.lcd_y = QtGui.QLCDNumber(self.tab_measure)
        self.lcd_y.setGeometry(QtCore.QRect(510, 380, 101, 40))
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lcd_y.sizePolicy().hasHeightForWidth())
        self.lcd_y.setSizePolicy(sizePolicy)
        self.lcd_y.setMinimumSize(QtCore.QSize(0, 40))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.lcd_y.setFont(font)
        self.lcd_y.setStyleSheet(_fromUtf8("color:#000000;"))
        self.lcd_y.setFrameShadow(QtGui.QFrame.Sunken)
        self.lcd_y.setSegmentStyle(QtGui.QLCDNumber.Flat)
        self.lcd_y.setObjectName(_fromUtf8("lcd_y"))
        self.tabWidget.addTab(self.tab_measure, _fromUtf8(""))
        self.tab_profile = QtGui.QWidget()
        self.tab_profile.setObjectName(_fromUtf8("tab_profile"))
        self.verticalLayoutWidget = QtGui.QWidget(self.tab_profile)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(-1, 9, 801, 411))
        self.verticalLayoutWidget.setObjectName(_fromUtf8("verticalLayoutWidget"))
        self.profile_layout = QtGui.QVBoxLayout(self.verticalLayoutWidget)
        self.profile_layout.setObjectName(_fromUtf8("profile_layout"))
        self.tabWidget.addTab(self.tab_profile, _fromUtf8(""))
        self.tab_options = QtGui.QWidget()
        self.tab_options.setObjectName(_fromUtf8("tab_options"))
        self.gridLayoutWidget = QtGui.QWidget(self.tab_options)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(10, 20, 381, 411))
        self.gridLayoutWidget.setObjectName(_fromUtf8("gridLayoutWidget"))
        self.gridLayout = QtGui.QGridLayout(self.gridLayoutWidget)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.lcdNumber_2 = QtGui.QLCDNumber(self.gridLayoutWidget)
        self.lcdNumber_2.setObjectName(_fromUtf8("lcdNumber_2"))
        self.gridLayout.addWidget(self.lcdNumber_2, 2, 3, 1, 1)
        self.pushButton_3 = QtGui.QPushButton(self.gridLayoutWidget)
        self.pushButton_3.setText(_fromUtf8(""))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(_fromUtf8(":/icons/assets/icons/up_arrow_32.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_3.setIcon(icon)
        self.pushButton_3.setIconSize(QtCore.QSize(32, 32))
        self.pushButton_3.setObjectName(_fromUtf8("pushButton_3"))
        self.gridLayout.addWidget(self.pushButton_3, 1, 5, 1, 1)
        self.label = QtGui.QLabel(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(18)
        self.label.setFont(font)
        self.label.setObjectName(_fromUtf8("label"))
        self.gridLayout.addWidget(self.label, 1, 1, 1, 1)
        spacerItem = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem, 1, 2, 1, 1)
        self.lcdNumber = QtGui.QLCDNumber(self.gridLayoutWidget)
        self.lcdNumber.setObjectName(_fromUtf8("lcdNumber"))
        self.gridLayout.addWidget(self.lcdNumber, 1, 3, 1, 1)
        self.label_2 = QtGui.QLabel(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(18)
        self.label_2.setFont(font)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.gridLayout.addWidget(self.label_2, 2, 1, 1, 1)
        self.pushButton = QtGui.QPushButton(self.gridLayoutWidget)
        self.pushButton.setText(_fromUtf8(""))
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(_fromUtf8(":/icons/assets/icons/down_arrow_32.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton.setIcon(icon1)
        self.pushButton.setIconSize(QtCore.QSize(32, 32))
        self.pushButton.setObjectName(_fromUtf8("pushButton"))
        self.gridLayout.addWidget(self.pushButton, 1, 4, 1, 1)
        self.pushButton_5 = QtGui.QPushButton(self.gridLayoutWidget)
        self.pushButton_5.setText(_fromUtf8(""))
        self.pushButton_5.setIcon(icon)
        self.pushButton_5.setIconSize(QtCore.QSize(32, 32))
        self.pushButton_5.setObjectName(_fromUtf8("pushButton_5"))
        self.gridLayout.addWidget(self.pushButton_5, 2, 5, 1, 1)
        self.pushButton_4 = QtGui.QPushButton(self.gridLayoutWidget)
        self.pushButton_4.setText(_fromUtf8(""))
        self.pushButton_4.setIcon(icon1)
        self.pushButton_4.setIconSize(QtCore.QSize(32, 32))
        self.pushButton_4.setObjectName(_fromUtf8("pushButton_4"))
        self.gridLayout.addWidget(self.pushButton_4, 2, 4, 1, 1)
        self.label_3 = QtGui.QLabel(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(18)
        self.label_3.setFont(font)
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.gridLayout.addWidget(self.label_3, 0, 1, 1, 1)
        self.lcdNumber_3 = QtGui.QLCDNumber(self.gridLayoutWidget)
        self.lcdNumber_3.setObjectName(_fromUtf8("lcdNumber_3"))
        self.gridLayout.addWidget(self.lcdNumber_3, 0, 3, 1, 1)
        self.pushButton_6 = QtGui.QPushButton(self.gridLayoutWidget)
        self.pushButton_6.setText(_fromUtf8(""))
        self.pushButton_6.setIcon(icon1)
        self.pushButton_6.setIconSize(QtCore.QSize(32, 32))
        self.pushButton_6.setObjectName(_fromUtf8("pushButton_6"))
        self.gridLayout.addWidget(self.pushButton_6, 0, 4, 1, 1)
        self.pushButton_7 = QtGui.QPushButton(self.gridLayoutWidget)
        self.pushButton_7.setText(_fromUtf8(""))
        self.pushButton_7.setIcon(icon)
        self.pushButton_7.setIconSize(QtCore.QSize(32, 32))
        self.pushButton_7.setObjectName(_fromUtf8("pushButton_7"))
        self.gridLayout.addWidget(self.pushButton_7, 0, 5, 1, 1)
        spacerItem1 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem1, 0, 2, 1, 1)
        spacerItem2 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem2, 2, 2, 1, 1)
        self.table_tx = QtGui.QTableView(self.tab_options)
        self.table_tx.setGeometry(QtCore.QRect(405, 21, 381, 411))
        self.table_tx.setStyleSheet(_fromUtf8("QScrollBar:vertical { width: 30px; }"))
        self.table_tx.setAlternatingRowColors(True)
        self.table_tx.setSelectionMode(QtGui.QAbstractItemView.MultiSelection)
        self.table_tx.setSelectionBehavior(QtGui.QAbstractItemView.SelectRows)
        self.table_tx.setObjectName(_fromUtf8("table_tx"))
        self.table_tx.horizontalHeader().setDefaultSectionSize(90)
        self.table_tx.horizontalHeader().setMinimumSectionSize(80)
        self.table_tx.horizontalHeader().setStretchLastSection(True)
        self.tabWidget.addTab(self.tab_options, _fromUtf8(""))
        self.button_close = QtGui.QPushButton(MeasurementsView)
        self.button_close.setGeometry(QtCore.QRect(675, 5, 110, 32))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.button_close.setFont(font)
        self.button_close.setObjectName(_fromUtf8("button_close"))

        self.retranslateUi(MeasurementsView)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QObject.connect(self.button_close, QtCore.SIGNAL(_fromUtf8("clicked()")), MeasurementsView.close)
        QtCore.QMetaObject.connectSlotsByName(MeasurementsView)

    def retranslateUi(self, MeasurementsView):
        MeasurementsView.setWindowTitle(_translate("MeasurementsView", "Measurements", None))
        self.button_measure.setText(_translate("MeasurementsView", "Measure", None))
        self.button_next_station.setText(_translate("MeasurementsView", "Next Station", None))
        self.button_prev_station.setText(_translate("MeasurementsView", "Prev Station", None))
        self.label_profile_num.setText(_translate("MeasurementsView", "Profile #", None))
        self.label_profile_num_val.setText(_translate("MeasurementsView", "TextLabel", None))
        self.label_current_point.setText(_translate("MeasurementsView", "Current Point", None))
        self.label_current_point_val.setText(_translate("MeasurementsView", "TextLabel", None))
        self.label_distance.setText(_translate("MeasurementsView", "Distance", None))
        self.label_distance_val.setText(_translate("MeasurementsView", "TextLabel", None))
        self.label_interval.setText(_translate("MeasurementsView", "Interval", None))
        self.label_interval_val.setText(_translate("MeasurementsView", "TextLabel", None))
        self.label_frames.setText(_translate("MeasurementsView", "Frames", None))
        self.label_frames_val.setText(_translate("MeasurementsView", "TextLabel", None))
        self.label_resolution.setText(_translate("MeasurementsView", "Resolution", None))
        self.label_resolution_val.setText(_translate("MeasurementsView", "TextLabel", None))
        self.label_tilt_x.setText(_translate("MeasurementsView", "X", None))
        self.label_tilt_y.setText(_translate("MeasurementsView", "Y", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_measure), _translate("MeasurementsView", "Measure", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_profile), _translate("MeasurementsView", "Profile", None))
        self.label.setText(_translate("MeasurementsView", "Frames", None))
        self.label_2.setText(_translate("MeasurementsView", "Resolution", None))
        self.label_3.setText(_translate("MeasurementsView", "Interval", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_options), _translate("MeasurementsView", "Options", None))
        self.button_close.setText(_translate("MeasurementsView", "Close", None))

import resources_rc
