# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '/Users/ecabuk/Projects/vlf/ui/spectrum_options.ui'
#
# Created by: PyQt4 UI code generator 4.11.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_SpectrumOptionsView(object):
    def setupUi(self, SpectrumOptionsView):
        SpectrumOptionsView.setObjectName(_fromUtf8("SpectrumOptionsView"))
        SpectrumOptionsView.resize(800, 480)
        SpectrumOptionsView.setAutoFillBackground(True)
        self.verticalLayoutWidget = QtGui.QWidget(SpectrumOptionsView)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(20, 9, 391, 401))
        self.verticalLayoutWidget.setObjectName(_fromUtf8("verticalLayoutWidget"))
        self.left_layout = QtGui.QVBoxLayout(self.verticalLayoutWidget)
        self.left_layout.setObjectName(_fromUtf8("left_layout"))
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.label_channels = QtGui.QLabel(self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(18)
        self.label_channels.setFont(font)
        self.label_channels.setObjectName(_fromUtf8("label_channels"))
        self.horizontalLayout.addWidget(self.label_channels)
        spacerItem = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.button_c_v = QtGui.QPushButton(self.verticalLayoutWidget)
        self.button_c_v.setMinimumSize(QtCore.QSize(0, 0))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.button_c_v.setFont(font)
        self.button_c_v.setText(_fromUtf8(""))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(_fromUtf8(":/icons/assets/icons/v.svg")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.button_c_v.setIcon(icon)
        self.button_c_v.setIconSize(QtCore.QSize(32, 32))
        self.button_c_v.setCheckable(True)
        self.button_c_v.setChecked(False)
        self.button_c_v.setObjectName(_fromUtf8("button_c_v"))
        self.horizontalLayout.addWidget(self.button_c_v)
        self.button_c_h = QtGui.QPushButton(self.verticalLayoutWidget)
        self.button_c_h.setMinimumSize(QtCore.QSize(0, 0))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.button_c_h.setFont(font)
        self.button_c_h.setText(_fromUtf8(""))
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(_fromUtf8(":/icons/assets/icons/h.svg")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.button_c_h.setIcon(icon1)
        self.button_c_h.setIconSize(QtCore.QSize(32, 32))
        self.button_c_h.setCheckable(True)
        self.button_c_h.setObjectName(_fromUtf8("button_c_h"))
        self.horizontalLayout.addWidget(self.button_c_h)
        self.button_c_vh = QtGui.QPushButton(self.verticalLayoutWidget)
        self.button_c_vh.setMinimumSize(QtCore.QSize(0, 0))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.button_c_vh.setFont(font)
        self.button_c_vh.setText(_fromUtf8(""))
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(_fromUtf8(":/icons/assets/icons/vh.svg")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.button_c_vh.setIcon(icon2)
        self.button_c_vh.setIconSize(QtCore.QSize(32, 32))
        self.button_c_vh.setCheckable(True)
        self.button_c_vh.setChecked(False)
        self.button_c_vh.setFlat(False)
        self.button_c_vh.setObjectName(_fromUtf8("button_c_vh"))
        self.horizontalLayout.addWidget(self.button_c_vh)
        self.left_layout.addLayout(self.horizontalLayout)
        spacerItem1 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.left_layout.addItem(spacerItem1)
        self.horizontalLayout_2 = QtGui.QHBoxLayout()
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        self.label_input_volume = QtGui.QLabel(self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(18)
        self.label_input_volume.setFont(font)
        self.label_input_volume.setObjectName(_fromUtf8("label_input_volume"))
        self.horizontalLayout_2.addWidget(self.label_input_volume)
        spacerItem2 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem2)
        self.bar_volume = QtGui.QProgressBar(self.verticalLayoutWidget)
        self.bar_volume.setMinimumSize(QtCore.QSize(110, 0))
        self.bar_volume.setProperty("value", 0)
        self.bar_volume.setTextVisible(False)
        self.bar_volume.setObjectName(_fromUtf8("bar_volume"))
        self.horizontalLayout_2.addWidget(self.bar_volume)
        self.button_vol_down = QtGui.QPushButton(self.verticalLayoutWidget)
        self.button_vol_down.setText(_fromUtf8(""))
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(_fromUtf8(":/icons/assets/icons/down_arrow_32.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.button_vol_down.setIcon(icon3)
        self.button_vol_down.setIconSize(QtCore.QSize(32, 32))
        self.button_vol_down.setObjectName(_fromUtf8("button_vol_down"))
        self.horizontalLayout_2.addWidget(self.button_vol_down)
        self.button_vol_up = QtGui.QPushButton(self.verticalLayoutWidget)
        self.button_vol_up.setText(_fromUtf8(""))
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap(_fromUtf8(":/icons/assets/icons/up_arrow_32.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.button_vol_up.setIcon(icon4)
        self.button_vol_up.setIconSize(QtCore.QSize(32, 32))
        self.button_vol_up.setObjectName(_fromUtf8("button_vol_up"))
        self.horizontalLayout_2.addWidget(self.button_vol_up)
        self.left_layout.addLayout(self.horizontalLayout_2)
        self.line_2 = QtGui.QFrame(SpectrumOptionsView)
        self.line_2.setGeometry(QtCore.QRect(0, 410, 801, 20))
        self.line_2.setFrameShape(QtGui.QFrame.HLine)
        self.line_2.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_2.setObjectName(_fromUtf8("line_2"))
        self.button_close = QtGui.QPushButton(SpectrumOptionsView)
        self.button_close.setGeometry(QtCore.QRect(350, 430, 110, 41))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.button_close.setFont(font)
        self.button_close.setObjectName(_fromUtf8("button_close"))
        self.table_tx = QtGui.QTableView(SpectrumOptionsView)
        self.table_tx.setGeometry(QtCore.QRect(420, 10, 361, 401))
        self.table_tx.setStyleSheet(_fromUtf8("QScrollBar:vertical { width: 30px; }"))
        self.table_tx.setFrameShape(QtGui.QFrame.Panel)
        self.table_tx.setFrameShadow(QtGui.QFrame.Raised)
        self.table_tx.setAlternatingRowColors(True)
        self.table_tx.setSelectionMode(QtGui.QAbstractItemView.MultiSelection)
        self.table_tx.setSelectionBehavior(QtGui.QAbstractItemView.SelectRows)
        self.table_tx.setObjectName(_fromUtf8("table_tx"))
        self.table_tx.horizontalHeader().setStretchLastSection(True)
        self.table_tx.verticalHeader().setVisible(False)

        self.retranslateUi(SpectrumOptionsView)
        QtCore.QObject.connect(self.button_close, QtCore.SIGNAL(_fromUtf8("clicked()")), SpectrumOptionsView.close)
        QtCore.QMetaObject.connectSlotsByName(SpectrumOptionsView)

    def retranslateUi(self, SpectrumOptionsView):
        SpectrumOptionsView.setWindowTitle(_translate("SpectrumOptionsView", "Spectrum Options", None))
        self.label_channels.setText(_translate("SpectrumOptionsView", "Channels", None))
        self.label_input_volume.setText(_translate("SpectrumOptionsView", "Input Volume", None))
        self.button_close.setText(_translate("SpectrumOptionsView", "Close", None))

import resources_rc
